Module2 task1
htmlacademy-adaptive/2057771-cat-energy-28 pull request #2
Opened 2023-08-20 15:44 UTC by vetarara

Сделала разметку всех страниц

2023-08-20 23:03 UTC, DoberBober commented on source/index.html
> +      <a class="main-header__logo"> <!-- скорее всего это должен быть отдельный блок, так как это изображение переиспользуются в футере? -->
Не, тут лучше оставить элементом.

2023-08-20 23:04 UTC, DoberBober commented on source/index.html
> +            <button class="lead__selection" type="button">Подобрать программу</button>
Ссылка.

2023-08-20 23:04 UTC, DoberBober commented on source/index.html
> +          <dl class="lead__list">
Это лучше вынести в отдельный блок. dl/dt - такое себе. Лучше сделай заголовком и параграфом.

2023-08-20 23:05 UTC, DoberBober commented on source/index.html
> +        </div>
Не хватает штуки со сравнением котов.

2023-08-20 23:06 UTC, DoberBober commented on source/index.html
> +            </li>
Это лучше вынести из social. Всё-таки это не соцсеть, а просто ссылка.

2023-08-20 23:07 UTC, DoberBober commented on source/catalog.html
> +          <h1 class="main-catalog__headline">Каталог продукции</h1>
Учитывая, что заголовок повторяется и в форме, имеет смысл вынести в отдельный блок.

2023-08-20 23:07 UTC, DoberBober commented on source/catalog.html
> +              <section class="card">
Секшн лишний. Класс card можешь замиксовать на лишке.

2023-08-20 23:08 UTC, DoberBober commented on source/catalog.html
> +                </a>
Лучше раздели на две ссылки: одна вокруг картинки, другая - в заголовке.

2023-08-20 23:09 UTC, DoberBober commented on source/catalog.html
> +                <button class="product__order" type="button">Заказать</button> <!-- не понимаю, по какому принципу назвать класс.
Ссылка.
По классам: тут и выше появился какой-то product, хотя блок называется card.

2023-08-20 23:09 UTC, DoberBober commented on source/catalog.html
> +          <section class="show-more">
Будет проще, если ты вставишь это внутрь списка, как лишку.

2023-08-20 23:10 UTC, DoberBober commented on source/catalog.html
> +            <h3 class="card__title">Показать еще 100500 товаров</h3>
`show-more__title`.

2023-08-20 23:10 UTC, DoberBober commented on source/catalog.html
> +            <button class="show-all" type="button">Показать все</button>
Ссылка. Класс - `show-more__XXX`.

2023-08-20 23:10 UTC, DoberBober commented on source/catalog.html
> +              <section class="extra-card">
Тоже секшн лишний. Класс замиксуй на лишке.

2023-08-20 23:12 UTC, DoberBober commented on source/catalog.html
> +                <button class="extra-product__order" type="button">Заказать</button>
Ссылка. Если хочешь общую кнопку сделать, вынеси её в отдельный блок. `product__order` тут использовать уже не получится.

2023-08-20 23:12 UTC, DoberBober commented on source/catalog.html
> +        <img class="gift" src="#" width="78" height="80" alt="Акция">
`action__gift`.

2023-08-20 23:12 UTC, DoberBober commented on source/catalog.html
> +  </body>
На странице каталога dl/dt не очень подходят, по-моему.

2023-08-20 23:13 UTC, DoberBober commented on source/program-selection.html
> +    <title>HTML Academy: Подбор программы Кэт энерджи</title> <!-- title здесь ведь должен отличаться от title на главной и в каталоге? -->
Ага.

2023-08-20 23:13 UTC, DoberBober commented on source/program-selection.html
> +    <header class="main-header"> <!--класс всё ещё main-header? в обучении отмечалось, что main-header - хэдер главной страницы.
Да, общий хедер везде.

2023-08-20 23:13 UTC, DoberBober commented on source/program-selection.html
> +          <form action="https://echo.htmlacademy.ru" method="post">
Форма на странице одна. Она оборачивает все поля.

2023-08-20 23:14 UTC, DoberBober commented on source/program-selection.html
> +              <input type="text" name="name" id="name-field" value="БАРСИК">
Связки лейбл_инпут оберни в див, чтобы сгруппировать. Этот див можешь сделать блоком, а лейбл и инпут - элементами этого блока.

2023-08-20 23:14 UTC, DoberBober commented on source/program-selection.html
> +              <input type="text" name="weight" id="weight-field" value="7">
value везде убери, пропиши placeholder.

2023-08-20 23:15 UTC, DoberBober commented on source/program-selection.html
> +            <option selected>сахарозаменитель</option>
Чекбоксы ж, не селект.)

2023-08-20 23:16 UTC, DoberBober commented on source/program-selection.html
> +        <input type="submit" value="Отправить заявку"> <!-- нормально ли то, что эта кнопка вне какой-либо формы?
Эта кнопка должна быть внутри единой формы. Кнопку и сноску про обязательные поля оберни в див, чтобы было проще.

2023-08-20 23:16 UTC, DoberBober requested changes
В целом, хорошо. С классами хорошо поработала. Чуть доработать структуру и можно принимать.

2023-08-22 00:29 UTC, vetarara commented
исправила

2023-08-22 00:30 UTC, vetarara commented on source/program-selection.html
> +            <option selected>сахарозаменитель</option>
Тут я делала не чекбокс, а мультиселект, так как это список, в котором нужно выбрать несколько вариантов. Поэтому там selected, а не checked

2023-08-22 14:18 UTC, merged